/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jacob_toolkit_toolkitforandroid_ndk_JniInterface */

#ifndef _Included_com_jacob_toolkit_toolkitforandroid_ndk_JniInterface
#define _Included_com_jacob_toolkit_toolkitforandroid_ndk_JniInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jacob_toolkit_toolkitforandroid_ndk_JniInterface
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jacob_toolkit_toolkitforandroid_ndk_JniInterface_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_jacob_toolkit_toolkitforandroid_ndk_JniInterface
 * Method:    changeString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jacob_toolkit_toolkitforandroid_ndk_JniInterface_changeString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jacob_toolkit_toolkitforandroid_ndk_JniInterface
 * Method:    changeFloatArray
 * Signature: ([F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_jacob_toolkit_toolkitforandroid_ndk_JniInterface_changeFloatArray
  (JNIEnv *, jobject, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
